from copy import deepcopy
from hashlib import sha256
from io import BytesIO
from unittest.mock import Mock

from PIL import Image
import pytest

from app import pdf_receipt_readonly as ro
from app.pdf_page_kind import PageKindConfirmation
from app.receipt_pdf_grouping import PageEvidence
from app.receipt_pdf_units import _digest
from app.models import ReceiptResult
from test_pdf_grouping_authority import context,request
from test_receipt_pdf_units import local_ocr,synthetic_pdf,kind_of

CATEGORIES=[('食費','食品')]

def setup(kinds=('medical','normal')):
    g,live,transport=context(kinds)
    view=g.display('drive-source-id')
    human=PageKindConfirmation(g)
    human.confirm(view['proposal'],{1:'医療',2:'一般'})
    view=g.regenerate_general('drive-source-id',lambda *_:{2:PageEvidence()})
    g.review(request(view))
    value=g.store.load();record=value['records'][_digest('drive-source-id')];p=record['proposal']
    unit=g.confirmed_units('drive-source-id')[0]
    expected={k:p[k] for k in ('source_file_id','source_content_hash','page_count','proposal_digest')}
    expected.update(binding=g.store.binding,grouping_revision=record['revision'],confirmation_digest=record['confirmation']['confirmation_digest'],unit_ids={2:unit.unit_id})
    content=synthetic_pdf(kinds)
    # PDF attachment/content is deterministically generated by the fixture.
    assert sha256(content).hexdigest()==p['source_content_hash']
    result=ReceiptResult(date='2026-09-01',merchant='テスト店',total=100,payment_method='現金',
                         items=[dict(name='商品',amount=100,major_category='食費',minor_category='食品')])
    analyze=Mock(return_value=(result,[result]))
    service=ro.ReadonlyPdfReceipts(g.store.load,Mock(return_value=content),analyze,CATEGORIES,expected,model='synthetic')
    return service,g,transport,analyze,value

def test_confirmed_single_rgb_page_only_and_replay_never_write(local_ocr):
    svc,g,t,ai,_=setup();before=t.payload;writes=t.writes;local_ocr.clear()
    first=svc.run(2);second=svc.run(2)
    assert first['status']==second['status']=='would_import'
    assert first['unit_id']==second['unit_id']
    assert svc.budget.peak_live_pages==1 and svc.budget.live_pages==0
    assert set(local_ocr)=={'normal'}  # p1 not rendered or observed
    png=ai.call_args.args[0]
    with Image.open(BytesIO(png)) as image:
        assert image.mode=='RGB' and image.info=={} and kind_of(image)=='normal'
    assert b'%PDF-' not in png and b'PRIVATE_ATTACHMENT_99' not in png
    assert t.payload==before and t.writes==writes
    assert first['accounting_allowed'] is first['medical_handoff_allowed'] is first['archive_allowed'] is False

@pytest.mark.parametrize('change',['unconfirmed','medical','hash','revision','digest','unit','page_hash'])
def test_stale_or_unconfirmed_never_send(local_ocr,change):
    svc,g,t,ai,value=setup();record=value['records'][_digest('drive-source-id')]
    if change=='unconfirmed':record['confirmation']=None;record['status']='held'
    elif change=='medical':svc.expected['unit_ids'][1]='fake'
    elif change=='hash':svc.load_source=Mock(return_value=b'%PDF-changed')
    elif change=='revision':svc.expected['grouping_revision']+=1
    elif change=='digest':svc.expected['confirmation_digest']='0'*64
    elif change=='unit':svc.expected['unit_ids'][2]='fake'
    elif change=='page_hash':
        svc.load_source=Mock(return_value=synthetic_pdf(('medical','payroll')))
        # Deliberately inconsistent fresh raster/source proof fails before send.
        svc.expected['source_content_hash']=sha256(svc.load_source()).hexdigest()
        record['proposal']['source_content_hash']=svc.expected['source_content_hash']
    svc.load_authority=Mock(return_value=value)
    outcome=svc.run(1 if change=='medical' else 2)
    assert outcome['status']=='authority_held';ai.assert_not_called()

def test_restrictive_automatic_kind_cannot_be_downgraded(local_ocr):
    svc,g,t,ai,value=setup(('medical','unknown'))
    report=svc.run(2)
    assert report['status']=='privacy_blocked';ai.assert_not_called()
    assert svc.budget.render_calls==0

@pytest.mark.parametrize('failure',['render','page_hash','exact_gate','ocr','adapter_gate'])
def test_payload_failure_never_calls_gemini(local_ocr,monkeypatch,failure):
    svc,g,t,ai,_=setup()
    if failure=='render':monkeypatch.setattr(ro,'_render_png',Mock(side_effect=ro.RenderHold('render_failed')))
    if failure=='page_hash':monkeypatch.setattr(ro,'_render_png',Mock(return_value=b'different raster'))
    if failure=='exact_gate':
        gate,_=ro._checked_gate(g.load_observations('drive-source-id',None).pages[1]._payload,'normal')
        monkeypatch.setattr(ro,'_checked_gate',Mock(return_value=(gate,False)))
    if failure=='ocr':monkeypatch.setattr(ro,'_extract_receipt_text',Mock(side_effect=ValueError('PRIVATE RAW')))
    if failure=='adapter_gate':ai.side_effect=ro.ReceiptPrivacyBlocked()
    report=svc.run(2)
    if failure!='adapter_gate':ai.assert_not_called()
    assert report['status'] in {'authority_held','privacy_blocked','analysis_failed'}
    assert 'PRIVATE RAW' not in str(report)

def test_mismatch_instability_adjustment_and_payment_require_review(local_ocr):
    svc,g,t,ai,_=setup()
    result,history=ai.return_value
    result=result.model_copy(update={'total':120,'payment_method':'PayPay'})
    ai.return_value=(result,[history[0],result])
    report=svc.run(2)
    assert report['status']=='would_need_review'
    assert not report['checks']['total_matches'] and not report['checks']['reread_stable']
    assert not report['checks']['payment_evidence_supported']

@pytest.mark.parametrize('change',['authority','source'])
def test_concurrent_change_after_gate_never_sends(local_ocr,change):
    svc,g,t,ai,value=setup()
    if change=='authority':
        held=deepcopy(value);r=held['records'][_digest('drive-source-id')]
        r['confirmation']=None;r['status']='held'
        svc.load_authority=Mock(side_effect=[value,held])
    else:svc.load_source=Mock(side_effect=[svc.load_source(),'changed'.encode()])
    assert svc.run(2)['status']=='authority_held'
    ai.assert_not_called()

def test_unverified_adjustment_is_not_balanced_into_import(local_ocr):
    svc,g,t,ai,_=setup();result,_=ai.return_value
    result=result.model_copy(update={'items':[result.items[0].model_copy(update={'name':'調整額'})]})
    ai.return_value=(result,[result])
    report=svc.run(2)
    assert report['status']=='would_need_review' and report['checks']['unverified_adjustment']

@pytest.mark.parametrize('status',[400,401,403,404,429,503])
def test_analysis_http_failure_keeps_only_numeric_status(local_ocr,status):
    from google.genai.errors import APIError
    svc,g,t,ai,_=setup();before=t.payload;writes=t.writes
    ai.side_effect=APIError(status,{'error':{'message':'PRIVATE_SECRET_OCR'}})
    report=svc.run(2)
    assert report['status']=='analysis_failed' and report['gemini_api_status']==status
    assert report['analysis_failure_kind']=='gemini_http_error'
    assert 'PRIVATE_SECRET_OCR' not in str(report)
    assert t.payload==before and t.writes==writes and ai.call_count==1

def test_fake_http_status_is_not_trusted(local_ocr):
    svc,_,_,ai,_=setup()
    error=RuntimeError('PRIVATE_SECRET_OCR');error.status_code=403
    ai.side_effect=error;report=svc.run(2)
    assert report['analysis_failure_kind']=='result_or_validation_error'
    assert 'gemini_api_status' not in report and 'PRIVATE_SECRET_OCR' not in str(report)
    assert report['analysis_failure_class']=='runtime'
    assert all(set(x)=={'file','line'} and '/' not in x['file'] and '\\' not in x['file']
               for x in report['analysis_failure_sites'])
