"""Preview-only projection of Payroll master-sync plans."""

from __future__ import annotations

from .materialization import (
    MaterializationOperation,
    MaterializationPlan,
    MaterializationPrecondition,
)
from .payroll_master_sync import PayrollMasterSyncPlan
from .payroll_sheets import SHEET_TITLES


PLAN_VERSION = "payroll-master-sync-v1"
_STANDARD_SHEET_KEY = "payroll_standard_items"
_ALIAS_SHEET_KEY = "payroll_item_aliases"


def _standard_payload(plan: PayrollMasterSyncPlan) -> list[dict[str, object]]:
    # ``created_at`` is runtime-generated by the existing code-master records.
    # It is intentionally not plan intent or plan identity.
    return [
        {
            "standard_item_id": item.standard_item_id,
            "standard_name": item.standard_name,
            "section": item.section,
            "value_type": item.value_type,
            "active": item.active,
        }
        for item in plan.would_add_standard_items
    ]


def _alias_payload(plan: PayrollMasterSyncPlan) -> list[dict[str, object]]:
    # As above, omit runtime-generated ``created_at`` from the pure plan.
    return [
        {
            "alias_id": alias.alias_id,
            "raw_item_name": alias.raw_item_name,
            "standard_item_id": alias.standard_item_id,
            "employer_id": alias.employer_id,
            "active": alias.active,
        }
        for alias in plan.would_add_aliases
    ]


def _preconditions(
    plan: PayrollMasterSyncPlan,
    *,
    candidate_ids: list[str],
) -> tuple[MaterializationPrecondition, ...]:
    return (
        MaterializationPrecondition("schema_ok", plan.schema_ok),
        MaterializationPrecondition("conflict_free", not bool(plan.conflict_unsafe)),
        MaterializationPrecondition("expected_candidate_ids", candidate_ids),
    )


def _target(sheet_key: str) -> dict[str, str]:
    return {
        "resource": "google_sheets",
        "sheet_key": sheet_key,
        "sheet_title": SHEET_TITLES[sheet_key],
    }


def payroll_master_sync_to_materialization_plan(
    plan: PayrollMasterSyncPlan,
) -> MaterializationPlan:
    """Project an existing master-sync preview without re-reading or writing."""

    if not isinstance(plan, PayrollMasterSyncPlan):
        raise TypeError("payroll_master_sync_plan_required")
    blocked = not plan.schema_ok or bool(plan.conflict_unsafe)
    blocked_reason = (
        plan.conflict_unsafe[0].reason if plan.conflict_unsafe else "sheet_schema_not_safe"
    ) if blocked else None
    operations: list[MaterializationOperation] = []
    if not blocked and plan.would_add_standard_items:
        standard_ids = [item.standard_item_id for item in plan.would_add_standard_items]
        operations.append(MaterializationOperation(
            "append_standard_items",
            "append_row",
            _target(_STANDARD_SHEET_KEY),
            {"items": _standard_payload(plan)},
            _preconditions(plan, candidate_ids=standard_ids),
        ))
    if not blocked and plan.would_add_aliases:
        alias_ids = [alias.alias_id for alias in plan.would_add_aliases]
        operations.append(MaterializationOperation(
            "append_aliases",
            "append_row",
            _target(_ALIAS_SHEET_KEY),
            {"items": _alias_payload(plan)},
            _preconditions(plan, candidate_ids=alias_ids),
        ))

    return MaterializationPlan(
        domain="payroll",
        plan_version=PLAN_VERSION,
        # Existing PayrollMasterSyncPlan is derived from code-master constants
        # and a Sheets snapshot, but carries no source identity/version.  Keep
        # this explicit instead of fabricating a file/hash/statement identity.
        source=None,
        operations=tuple(operations),
        blocked=blocked,
        blocked_reason=blocked_reason,
        provenance={
            "code_standard_item_count": plan.code_standard_item_count,
            "sheets_active_standard_item_count": plan.sheets_active_standard_item_count,
            "code_exact_alias_count": plan.code_exact_alias_count,
            "sheets_active_alias_count": plan.sheets_active_alias_count,
            "already_present": [dict(entry) for entry in plan.already_present],
            "conflicts": [issue.model_dump(mode="json") for issue in plan.conflict_unsafe],
        },
    )
